language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .[test]

script:
  - coverage run -m unittest tests
  - coverage report --show-missing
  - pip-module-scanner -p tests/project/
